package com.dogukanincee.ormlite_implementation

import com.j256.ormlite.field.DatabaseField
import com.j256.ormlite.table.DatabaseTable

/**
 * Represents a person in the database.
 *
 * @property id The unique ID of the person, generated by the database.
 * @property name The name of the person.
 * @property age The age of the person.
 */
@DatabaseTable(tableName = "persons")
data class Person(
    @DatabaseField(generatedId = true)
    val id: Int? = null,
    @DatabaseField
    val name: String = "", // default value for name
    @DatabaseField
    val age: Int = 0 // default value for age
) {
    // Default constructor required by ORMLite
    constructor() : this(null, "", 0)
}