package com.dogukanincee.ormlite_implementation.model

import com.j256.ormlite.field.DatabaseField
import com.j256.ormlite.table.DatabaseTable

/**
 * Represents a person in the database.
 *
 * @property id The unique ID of the person, generated by the database.
 * @property name The name of the person.
 * @property age The age of the person.
 */
@DatabaseTable(tableName = "persons")
data class Person(
    @DatabaseField(generatedId = true)
    val id: Int = 0,

    @DatabaseField(canBeNull = false)
    val name: String,

    @DatabaseField(canBeNull = false)
    val age: Int
) {
    // Default constructor required by ORMLite
    constructor() : this(0, "", 0)
}